config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:create, :new, :index, :show]

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'welcome' => :welcome
  end

  resources :savings, only: [:create, :new, :index]
  resources :users, only: [:create, :new, :show, :index]
  
  controller :savings do
    get 'savings_no_project' => :savings_with_no_project
  end
  
  root 'users#show'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :savings, foreign_key: :author_id, class_name: 'Saving'

  has_secure_password
  has_attached_file :image, styles: { medium: '300x300#', thumb: '100x100#' }, default_url: 'user.svg'
  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png']
  validates :name, presence: true, length: { minimum: 5, maximum: 200 }, uniqueness: true
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "The User #{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "The User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :authorize, only: %i[create new]

  def index
    @users = User.order(:name)
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.update(image_url: @user.image.url)
        format.html { redirect_to login_path, notice: "#{@user.name} was created succesfully." }
      else
        format.html { render :new }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(current_user.id)
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :image, :password, :password_confirmation)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= javascript_include_tag 'show_image' %>
<%= form_with(model: user, local: true, id: 'User') do |form| %>
  <div id="image" class="d-none mt-5">
    <br>
    <img id="img-upload" alt="preview" class="w-50 d-block mx-auto">
    <br>
  </div>

  <%= form.file_field :image, class: 'custom-file-input mb-3',onChange: 'preview_picture()' %>
  <%= form.label :image, "Upload picture", class: 'custom-file-label' %>
  <%= form.text_field :name, class: 'border-white w-100 rounded mb-0 py-4 pl-5 my-3', placeholder: 'Type your Unique username' %>
  <%= form.password_field :password, size: 40, class: 'pl-5  border-white w-100 rounded mb-0 py-4 my-3', placeholder: 'Type your password' %>
  <%= form.password_field :password_confirmation,
                          id: :user_password_confirmation,
                          size: 40,
                          class: 'pl-5 border-white w-100 rounded mb-0 py-4 my-3',
                          placeholder: 'Type your password again' %>

  <% @page_button = (form.submit 'Next', class:"submit", form: 'User').html_safe %>

  <% if user.errors.any? %>
    <div id="error_explanation" class="m-5 border border-danger rounded p-5">
      <h2><%= pluralize(user.errors.count, "error") %> prevented the user from being saved, please correct the following:</h2>

      <ul class='pl-0'>
        <% user.errors.full_messages.each do |message| %>
          <p class='mx-0 px-0 text-danger text-bold'><%= message %></p>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<% @page_name = 'REGISTER' %>

<div class="row <%= controller.action_name %>">
    <section class = 'col-12 px-0 mx-0'>
        <%= render 'form', user: @user %>
    </section>
</div>

app/views/users/show.html.erb
<div class="d-flex flex-column justify-content-center mx-0 px-0 <%= controller.action_name %>">
  <%= image_tag current_user.image.url, class:"profile text-white"%>

  <hr>
  <h2 class = 'w-100 text-center text-white my-4'><%= current_user.name %></h2>
  <ul class="nav">
      <div class ='my-4 w-100 d-flex align-items-center justify-content-center px-4'>
        <i class="fas fa-piggy-bank p-4 text-white"></i>
        <span class="w-100 border-bottom border-white"><%= link_to 'All my savings', savings_path, class: 'text-white' %></span>
      </div>
      <div class ='my-4 w-100 d-flex align-items-center justify-content-center px-4'>
        <i class="fas fa-tasks p-4 text-white"></i>
        <span class="w-100 border-bottom border-white"><%= link_to 'Contributions without project', savings_no_project_path, class: 'text-white' %></span>
      </div>
      <div class ='my-4 w-100 d-flex align-items-center justify-content-center px-4'>
        <i class="fas fa-user-friends p-4 text-white"></i>
        <span class="w-100 border-bottom border-white"><%= link_to 'All projects', projects_path, class: 'text-white' %></span>
      </div>
      <div class ='my-4 w-100 d-flex align-items-center justify-content-center px-4'>
        <i class="fas fa-sign-out-alt p-4 text-white"></i>
        <span class="w-100 border-bottom border-white"><%= link_to 'Sign out', logout_path, method: :delete, data: { confirm: 'Are you sure to logout?' }, class: 'text-white' %></span>
      </div>    
  </ul>
</div>