config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:create, :new, :index, :show]

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'welcome' => :welcome
  end

  resources :savings, only: [:create, :new, :index]
  resources :users, only: [:create, :new, :show, :index]
  
  controller :savings do
    get 'savings_no_project' => :savings_with_no_project
  end
  
  root 'users#show'
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :savings
  belongs_to :user

  validates :name, :goal, presence: true
  validates :name, length: { minimum: 5, maximum: 200 }
  validates :goal, numericality: { greater_than_or_equal_to: 1 }

  has_attached_file :image, styles: { medium: '300x300#', thumb: '100x100#' }, default_url: 'user.svg'
  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png']

  scope :ordered_by_name, -> { order(name: :asc) }
  scope :rest_of_projects, ->(user_id) { where.not('user_id=?', user_id).ordered_by_name }

  def self.get_savings(project)
    savings = project.savings.ordered_by_date_savings.includes(:author)
    pluck_to_hash(savings.pluck(:name, :amount, :created_at, 'users.name', 'users.image_url'))
  end

  def self.user_projects(user)
    pluck_to_hash(user.projects.ordered_by_name.pluck(:name, :goal, :created_at, :id, :image_url))
  end

  def self.other_projects(user)
    pluck_to_hash(Project.rest_of_projects(user.id).pluck(:name, :goal, :created_at, :id, :image_url))
  end

  def self.pluck_to_hash(pluck)
    pluck.map! { |s| { name: s[0], goal: s[1], date: s[2].strftime('%b-%d-%Y'), id: s[3], img: s[4] } }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @user_projects = Project.user_projects(current_user)
    @other_projects = Project.other_projects(current_user)
  end

  def show
    @project = Project.find(params[:id])
    @savings = Project.get_savings(@project)
    @total_savings = @project.savings.sum(:amount)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        @project.update(image_url: @project.image.url)
        format.html { redirect_to projects_path, notice: "The project #{@project.name} was created." }
      else
        format.html { render :new }
      end
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :image, :goal)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_savings_amount_sum(project)
    project.savings.sum(:amount)
  end

  def percentage_completed(project)
    (project_savings_amount_sum(project) / project.goal) * 100
  end

  def goal_completed(project)
    (project_savings_amount_sum(Project.find(project[:id])) / Project.find(project[:id]).goal) * 100
  end
end

app/views/projects/_form.html.erb
<%= javascript_include_tag 'show_image' %>
<%= form_with(model: project, local: true, id: 'Project') do |form| %>
  <div id="image" class="d-none mt-5">
    <br>
    <img id="img-upload" alt="preview" class="w-50 d-block mx-auto">
    <br>
  </div>

  <%= form.file_field :image, class: 'custom-file-input mb-3',onChange: 'preview_picture()' %>
  <%= form.label :image, "Upload picture", class: 'custom-file-label' %>
  <%= form.text_field :name, class: 'border-white w-100 rounded mb-0 py-4 pl-5 my-3', placeholder: 'Type the project name' %>
  <%= form.number_field :goal, class: 'border-white w-100 rounded mb-0 py-4 pl-5 my-3', placeholder: "Project's goal" %>

  <% @page_button = (form.submit 'Save', class:"submit", form: 'Project').html_safe %>

  <% if project.errors.any? %>
    <div id="error_explanation" class="m-5 border border-danger rounded p-5">
      <h2><%= pluralize(project.errors.count, "error") %> prevented the project from being saved, please correct the following:</h2>

      <ul class='pl-0'>
        <% project.errors.full_messages.each do |message| %>
          <p class='mx-0 px-0 text-danger text-bold'><%= message %></p>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/projects/_savings.html.erb
<div class = 'bg-white p-5'>
  <h3>Total: <%= number_to_currency(@total_savings, precision: 0) %></h3>
</div>

<div class='d-flex flex-column justify-content-around my-3'>
  <%= message_if_no_projects(@savings) %>
  <% @savings.each do |saving| %>
    <div class='d-flex justify-content-between my-3 bg-white rounded p-5 shadow align-item-center'>
      <%= render_saving_img(saving) %>
      <div class="d-flex flex-column justify-content-between align-items-start p-2">
        <p>By: <%= saving[:id] %></p>
        <p><%= saving[:name] %></p>
        <p><%= saving[:date] %></p>
      </div>
      <div class="d-flex flex-column justify-content-between align-items-start p-3">
        <%= number_to_currency(saving[:goal], precision: 0) %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Add a saving", new_saving_path, class:'btn btn-success w-100 px-3 py-4 my-3'%>

app/views/projects/index.html.erb
<% @page_name = 'PROJECTS' %>

<div class="<%= controller.action_name %>">
    <section class = 'col-12 p-0'>

      <div class = 'bg-white p-5'>
        <h3>My Projects</h3>
      </div>
      <div class='d-flex flex-column justify-content-around my-3'>
        <%= message_if_no_projects(@user_projects) %>

        <% @user_projects.each do |project| %>
          <div class='d-flex justify-content-between my-3 bg-white rounded p-5 shadow'>
            <%= render_img(project) %>
            <div class="d-flex flex-column justify-content-between align-items-start p-3">
              <p><%= project[:name] %></p>
              <p><%= project[:date] %></p>
            </div>
            <div class="d-flex flex-column justify-content-between align-items-start p-3">
              <p>Goal: <%= number_to_currency(project[:goal], precision: 0) %></p>
              <p>Saved: <%= number_to_percentage(goal_completed(project), precision: 0) %></p>
            </div>
          </div>
        <% end %>        
      </div>

      <div class = 'bg-white p-5'>
        <h3>Other Projects</h3>
      </div>
      <div class='d-flex flex-column justify-content-around my-3'>
        <%= message_if_no_projects(@other_projects) %>
          <% @other_projects.each do |project| %>
            <div class='d-flex justify-content-between my-3 bg-white rounded p-5 shadow'>
              <%= render_img(project) %>
              <div class="d-flex flex-column justify-content-between align-items-start p-3">
                <p><%= project[:name] %></p>
                <p><%= project[:date] %></p>
              </div>
              <div class="d-flex flex-column justify-content-between align-items-start p-3">
                <p>Goal: <%= number_to_currency(project[:goal], precision: 0) %></p>
                <p>Saved: <%= number_to_percentage(goal_completed(project), precision: 0) %></p>
              </div>
            </div>
          <% end %>
      </div>

      <%= link_to "Create a Project", new_project_path, class:'btn btn-success w-100 px-3 py-4 my-3'%>
    </section>
</div>

app/views/projects/new.html.erb
<% @page_name = 'ADD A PROJECT' %>

<div class="<%= controller.action_name %>">
    <section class = 'col-12 p-0'>
        <%= render 'form', project: @project %>
    </section>
</div>

app/views/projects/show.html.erb
<% @page_name = "Project #{@project.name}" %>

<div class="d-flex flex-column justify-content-center mx-0 px-0 <%= controller.action_name %>">
  <%= image_tag @project.image.url, class:"project-picture"%>

  <div class = 'bg-white p-5 my-3'>
    <h3>Total Completed: <%= number_to_percentage(percentage_completed(@project), precision: 0) %></h3>
    <div class="progress shadow-lg">
      <div class="progress-bar progress-bar-striped bg-success progress-bar-animated"
          role="progressbar"
          style="width:<%= number_to_percentage(percentage_completed(@project), precision: 0) %>"
          aria-valuenow="<%= percentage_completed(@project) %>"
          aria-valuemin="0"
          aria-valuemax="100">
      </div>
    </div>
  </div>

  <div class = 'bg-white p-5 my-3'>
    <h3>Goal: <%= number_to_currency(@project.goal, precision:0 ) %></h3>
  </div>

  <%= render 'savings', savings: @savings %>

</div>